version: "3.3"
services:
  els-service:
    image: saimanojsuper/employee-eureka-service:1.0
    container_name: employee-eureka-service 
    ports:
      - 8761:8761
    networks:
      - consumer-producer
    #environment:
      #DOCKER_HOST : tcp://$HOST:2376
  
  producer:
    image: saimanojsuper/employee-producer-service:1.0
    container_name: employee-producer-service
    ports:
      - 8810:8810
    networks:
      - consumer-producer 
    depends_on:
      - els-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://els-service:8761/eureka
      #DOCKER_HOST : tcp://$HOST:2376
    
  consumer:
    image: saimanojsuper/employee-consumer-service:1.0
    container_name: employee-consumer-service
    ports:
      - 8820:8820
    networks:
      - consumer-producer
    depends_on:
      - els-service
      - producer
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://els-service:8761/eureka
      #DOCKER_HOST : tcp://$HOST:2376

networks:
  consumer-producer:
